### ISSUE TITLE
How to change the ticker from underline to default?

### ISSUE THREAD

**Issue by EddyHamzich-zz** [bmalehorn/vscode-vimspired#4]
Love this extension the only thing that I can't get used to is the underline ticker instead of " | "... Is it possible to change that ?

**Comment by bmalehorn** [comment]
Hey man, awesome to see someone enjoying this extension!

You're probably right, it shouldn't mess with the default cursor.

I just updated the extension to default to the "|" cursor. You can update your extension by running Ctrl-Shift-P "extensions: update all extensions".

I also added the ability to customize the insert & normal mode cursors. For example, you can get the underline behavior back with:

```json
"vimspired.insertCursorStyle": "underline"
```

**Comment by EddyHamzich-zz** [comment]
awesome thanks! I gave your extension a 5 star rating!
