### ISSUE TITLE
Support for type command

### ISSUE THREAD

**Issue by njoppi2** [bmalehorn/vscode-vimspired#7]
Man I LOVE your extension. Really! But there's just one thing that really bothers me, I cannot use the "type" comand while in vimspired mode, which isn't that bad in some cases (which I can get out of the insert mode, type and go back to normal mode), but I face some situations that makes this the only solution, and I think it would be a very nice feature! Btw, I've never done anything extension related but if you need any help/ideas with your extension I'd love to help :)

**Comment by bmalehorn** [comment]
@njoppi2 Awesome, thanks for saying so! I know there's some people out there using the extension, but it's always nice to hear from users.

I'm not surprised the `type` command isn't working - vimspired overrides the `type` command to listen on key inputs. However, there is a workaround:

1. Cmd+Shift+P / Ctrl+Shift+P
2. Preferences: Open Keyboard Shortcuts (JSON)
3. copy/paste this keybinding:
```json
  {
    "key": "ctrl+enter",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {
      "snippet": "hello world"
    }
  }
```
Then when you press ctrl+enter, it will insert the snippet "hello world".

You can also bind it to a vimspired keybinding. For example, this binds it to the key `1`:

```json
    "1": {
      "command": "editor.action.insertSnippet",
      "args": {
        "snippet": "hello world"
      }
    },
```

I'm not sure there's a way for vimspired to work without overriding `type`. When I was creating this package I spent a while trying to figure out how to override all inputs. I eventually looked at how the Vim extension worked, and it turns out they override `type` ([here](https://github.com/VSCodeVim/Vim/blob/e3e56eeb443a8c17ebce2a926aea658829edf08e/extension.ts#L313)), so that's what I did.

> Btw, I've never done anything extension related but if you need any help/ideas with your extension I'd love to help :)

Cool! I don't have any outstanding work to be done, but I could use some ideas: is there anything you miss from a previous editor? Or something you can't create in vimspired? What does your config look like?

**Comment by njoppi2** [comment]
Using snippets worked, thanks!!

So, there are a few thing that I actually wrote down to give to you as ideas hahha
The first would be to have an acessible "when" mode to other keybings, like this:
```
   {
      "command": "multiCommand.n",
      "key": "\\ n",
      "when": "**inVimspiredNormalMode** && !findInputFocussed"
   },
```
this would be really nice in some situations, one of mine in particular is that I'm using alt+j, alt+k, alt+l and alt+i as cursor movements while I'm im insert mode, but I'd like them to have a different purpose while I'm in normal mode, since the actuall keys (j, k, l, i) I already use to move.

Another thing that would help is when I write something like this:
```
"g": {
       "q": "breadcrumbs.focusAndSelect",
}
```
If I press "g", and "j" (to go left), the "j" doesn't work, then I have repeat a lot of possible commands that I may do after pressing "g", as a workaround:
```
"g": {
       "q": "breadcrumbs.focusAndSelect",
       "i": { "selecting": "cursorUpSelect", "default": "cursorUp" },
       "j": { "selecting": "cursorLeftSelect", "default": "cursorLeft" },
       "k": { "selecting": "cursorDownSelect", "default": "cursorDown" },
       "l": { "selecting": "cursorRightSelect", "default": "cursorRight" },
       "v": "editor.action.clipboardPasteAction",
       "f": "editor.action.moveSelectionToNextFindMatch",
       "a": {"selecting": "cancelSelection", "default": "undo"},
       "s": "deleteLeft",
       " ": ["deleteLeft", "vimspired.enterInsert"],
}
```

Lastly, this would be pretty cool too:
```
"type a" → do this command
"type a while pressing g" → do this other thing
```
but this seems really hard to do hahaha

I noticed just now that there are other commands besides the ones documented in "Feature Contributions", I'm really curious about what the "vimspired.swapActiveAndAnchor" does, so if you could document those it would be great :D

About my config, it's very big and I'm constantly putting more things in it, I use your extension with some other ones, and I'm really enjoying the result :), the extensions are: "Selecty By" by rioj7, it's really uselfull when I want to select everything inside (or containg) braces, brackets, quotes... it's awesome. "MetaGoGo", amazing, makes me able to navigate without the mouse very fast. "GoGo cursor savepoints": just downloaded this, so I couldn't do much yet, but basically, when I enter normal mode, it saves the cursor location, then when going back to insert mode, I can do 2 things, just change the mode, or go back to the last cursor location before it went normal mode. "Multiple Copy Paste", makes me able to store more than one thing at the same time, pretty nice too.
But if you want I can send my config too hehehe

**Comment by bmalehorn** [comment]
> The first would be to have an acessible "when" mode to other keybings

Ah, there's actually an (undocumented) way to do that already! The variable is `vimspired.normal`:

```json
  {
    "key": "ctrl+i",
    "command":"editor.action.insertSnippet",
    "when": "vimspired.normal",
    "args": {
      "snippet": "hello world"
    }
  }
```
> 
> Another thing that would help is when I write something like this:
> 
> ```
> "g": {
>        "q": "breadcrumbs.focusAndSelect",
> }
> ```
> 
> If I press "g", and "j" (to go left), the "j" doesn't work, then I have repeat a lot of possible commands that I may do after pressing "g", as a workaround:

Ok, so right now when you press "g" and then "j", it will:
1. reset you back to the root

but you want:
1. reset you back to the root
2. run the "j" command

Is that correct?

I'm wondering why you'd want this. The point of having a prefix like "g" is that you can map a whole other set of keybindings ON TOP OF your regular keybindings. But if all your regular keybindings are under "g", then you don't have any space left for "g" keybindings.

> 
> Lastly, this would be pretty cool too:
> 
> ```
> "type a" → do this command
> "type a while pressing g" → do this other thing
> ```
> 
> but this seems really hard to do hahaha

Yeah unfortunately I don't think this is exposed in the VSCode extension API. We only have "type" events, not key down and key up events.

> 
> I noticed just now that there are other commands besides the ones documented in "Feature Contributions", I'm really curious about what the "vimspired.swapActiveAndAnchor" does, so if you could document those it would be great :D

Vimspired started out as a bunch of commands I found helpful, then eventually morphed into a real extension intended for other people to make their own keybindings. `vimspired.swapActiveAndAnchor` works when you're highlighting text and moves the cursor to the other side of the text:

![Peek 2020-06-09 00-17](https://user-images.githubusercontent.com/3344958/84118080-5792cf00-a9e7-11ea-97d7-f5c0321605b8.gif)

It's really got nothing to do with the rest of vimspired, I just haven't bothered to spin it out into its own extension like I did with [Scroll Viewport](https://marketplace.visualstudio.com/items?itemName=bmalehorn.scroll-viewport).

> 
> About my config, it's very big and I'm constantly putting more things in it, I use your extension with some other ones, and I'm really enjoying the result :), the extensions are: "Selecty By" by rioj7, it's really uselfull when I want to select everything inside (or containg) braces, brackets, quotes... it's awesome. "MetaGoGo", amazing, makes me able to navigate without the mouse very fast. "GoGo cursor savepoints": just downloaded this, so I couldn't do much yet, but basically, when I enter normal mode, it saves the cursor location, then when going back to insert mode, I can do 2 things, just change the mode, or go back to the last cursor location before it went normal mode. "Multiple Copy Paste", makes me able to store more than one thing at the same time, pretty nice too.
> But if you want I can send my config too hehehe

Those extensions look pretty cool, thanks for sharing them!

**Comment by njoppi2** [comment]
Hey man sorry for the late answer,
> Ah, there's actually an (undocumented) way to do that already! The variable is `vimspired.normal`:

Thanks for sharing! I'm using it a lot now

> I'm wondering why you'd want this. The point of having a prefix like "g" is that you can map a whole other set of keybindings ON TOP OF your regular keybindings. But if all your regular keybindings are under "g", then you don't have any space left for "g" keybindings.

This may be a little hard to explain, I have this configuration in my vimspired:
```
"d": {
   "selecting": ["cancelSelection", "editor.action.addSelectionToNextFindMatch"],
   "default":[
      ["cursorRight", "cursorWordPartLeft", "cursorWordPartRightSelect"],
      {
         "d": ["cursorWordLeft", "cursorWordRightSelect"],
          //A lot more commands here
      }
   ]
}
```

What this does is, if I go to a word like ThisWordRightHere, and press "d", inside the word Right, it only selects "Right", camelCase style, but if I press "d" again, it'll select the whole word.
So, if I press "d" twice, it'll get out of this context, and I'll be able to acces all my commands on the "root" context, BUT, if I want to realize commands with only the camelCase selected text, I'll have to paste all my commands inside there, like this:

```
"d": {
   "selecting": ["cancelSelection", "editor.action.addSelectionToNextFindMatch"],
   "default":[
      ["cursorRight", "cursorWordPartLeft", "cursorWordPartRightSelect"],
      {
      "i": "cursorUpSelect", "j": "cursorLeftSelect", "k": "cursorDownSelect", "l": "cursorRightSelect", "o": "cursorWordPartRightSelect", "h": "cursorWordPartLeftSelect",
         " ": ["deleteLeft", "vimspired.enterInsert"],
         "c": ["editor.action.clipboardCopyAction", "cancelSelection"],"v": "editor.action.clipboardPasteAction", "»": ["extension.multipleCopy1", "deleteLeft"], "©": { "default": ["expandLineSelection", "extension.multipleCopy1", "cancelSelection"], "selecting": ["extension.multipleCopy1", "cancelSelection"] }, "“": "extension.multiplePaste1", "ç": { "default": ["expandLineSelection", "extension.multipleCopy2", "cancelSelection"], "selecting": ["extension.multipleCopy2", "cancelSelection"] }, "ǘ": "extension.multiplePaste2", "C": { "default": ["expandLineSelection", "extension.multipleCopy3", "cancelSelection"], "selecting": ["extension.multipleCopy3", "cancelSelection"] }, "V": "extension.multiplePaste3",
         "q": [
            ["expandLineSelection"],
            {
               "i": [
                  "cancelSelection",
                  {"command": "cursorMove",
                     "args": {
                        "to": "up",
                        "by": "wrappedLine",
                        "value": 2,
                        "select": true,
                        }
                     },
		  "cursorHomeSelect"],
		  "k": "cursorDownSelect",
	      }
	 ],
	 "I": "metaGo.spaceBlockSelectUp",
	 "K": "metaGo.spaceBlockSelectDown",
	 "ð": ["editor.action.addSelectionToNextFindMatch"],
	 "f": ["metaGo.bookmark.clearInFile", "metaGo.bookmark.toggle", { "selecting": "editor.action.moveSelectionToNextFindMatch", "default": ["metaGo.goto", "cursorUndo", "expandLineSelection"] }],
	 "a": {"selecting": "cancelSelection", "default": "undo"},
	 "g": {
	    "g": ["metaGo.bookmark.jumpToNext", "metaGo.bookmark.jumpToNext"],
	    "j": { "selecting": "cursorHomeSelect", "default": "cursorHome" },
	    "l": { "selecting": "cursorEndSelect", "default": "cursorEnd" },
	    "i": { "selecting": "cursorWordPartRightSelect", "default": "cursorWordPartRight" },
            "k": { "selecting": ["vimspired.swapActiveAndAnchor", "cursorWordPartLeftSelect", "vimspired.swapActiveAndAnchor"], "default": "cursorWordPartLeft" },
         }
         "d": ["cursorWordLeft", "cursorWordRightSelect"],
      },
   ]
},
```

> Vimspired started out as a bunch of commands I found helpful, then eventually morphed into a real extension intended for other people to make their own keybindings. `vimspired.swapActiveAndAnchor` works when you're highlighting text and moves the cursor to the other side of the text:

This is veeery usefull indeed, if you look the code above, I'm already using it hehe. Can you say what the others do too? Or do you plan to remove them in future updates of the extension?

One issue I noticed this week,  there seems to be some issues with multiCursors/selections, for example if I use the classic Ctrl+D command,  and toggle to the insert mode, all my cursors go away, if there's text being selected. Is there a workaround for this?

Btw, I'm using your extension to completely replace mouse use, and it's going great!

**Comment by njoppi2** [comment]
e's actually an (undocumented) way to do that already! The variable is vimspired.normal:

  {
    "key": "ctrl+i",
    "command":"editor.action.insertSnippet",
    "when": "vimspired.normal",
    "args": {
      "snippet": "hello world"
    }
  }
Another thing that would he

**Comment by bmalehorn** [comment]
```jsonc
"d": {
   "selecting": ["cancelSelection", "editor.action.addSelectionToNextFindMatch"],
   "default":[
      ["cursorRight", "cursorWordPartLeft", "cursorWordPartRightSelect"],
      {
         "d": ["cursorWordLeft", "cursorWordRightSelect"],
          //A lot more commands here
      }
   ]
}
```

Ah, I never considered using it this way - executing some code and then landing in a keymap. But sure, why wouldn't that work?

I get the feature you want now - retrying keybindings on the root keybinding if they fail. However I'd want to hear from a few other people that they'd want this feature to add it - it seems a bit specific to your setup.

It still seems interesting though, so I made a branch where you can test it out. Here's how you can install it:


2. `git clone https://github.com/bmalehorn/vscode-vimspired`
3. `cd vscode-vimspired`
0. `git checkout retry-on-root`
4. `yarn install`
5. `yarn bootstrap`
1. uninstall Vimspired
6. `ln -sv $PWD ~/.vscode/extensions/`
7. reload VSCode

> Can you say what the others do too? Or do you plan to remove them in future updates of the extension?

Sure.
`vimspired.toggleSelection`, `vimspired.cancelSelection`: These are basically a simplified version of Vim's "visual mode".

In VSCode, when you're selecting you must always select at least 1 character. There's no way to trigger the "selecting" branch while selecting 0 characters. When you call `vimspired.toggleSelection`, you will trigger the "selecting" branch even without highlighting any text.

This is useful for kick-starting a selection, without having to first select a word or line:

```jsonc
    "t": "vimspired.toggleSelection",
    "j": {
      "selecting": "cursorDownSelect",
      "default": "cursorDown"
    },
    "k": {
      "selecting": "cursorUpSelect",
      "default": "cursorUp"
    },
```
![Peek 2020-06-19 00-16](https://user-images.githubusercontent.com/3344958/85107176-61c08480-b1c2-11ea-8973-e51f06abc47c.gif)

`vimspired.copyWord`: This copies the current word under the cursor, without moving the cursor. Like `vimspired.swapActiveAndAnchor` it doesn't really have anything to do with the rest of Vimspired.

Feel free to use these commands. If I remove them from Vimspired I'll re-publish them as separate extensions.

> One issue I noticed this week, there seems to be some issues with multiCursors/selections, for example if I use the classic Ctrl+D command, and toggle to the insert mode, all my cursors go away, if there's text being selected. Is there a workaround for this?

Ah yep, multicursor support is pretty buggy. But now that you mention it, I tracked it this bug and fixed it! This was a big annoyance for me too.

> Btw, I'm using your extension to completely replace mouse use, and it's going great!

Thanks, that's the goal - hackers coming up with wild keymaps tuned to how they use the editor.

**Comment by njoppi2** [comment]
Awesome, thank's! You helped me a lot with this responses.

**Comment by bmalehorn** [comment]
Great, going to close out this issue for completeness. Feel free to reopen / open another issue if you have other suggestions.
